# Generated by Django 3.0.5 on 2020-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='type',
            field=models.CharField(blank=True, choices=[('Labo', 'Laboratoire'), ('Ecole', 'Ecole'), ('Platforme', 'Platforme'), ('Service', 'Service'), ('Recherche', 'Recherche'), ('Composante', 'Composante Universitaire')], default='', help_text="Type d'affiliation", max_length=20),
        ),
    ]
