# Generated by Django 3.0.5 on 2020-05-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ref_int', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_man', models.CharField(blank=True, max_length=50, null=True)),
                ('localisation', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='type',
            field=models.CharField(blank=True, choices=[('Labo', 'Laboratoire'), ('Ecole', 'Ecole'), ('Platforme', 'Platforme'), ('Service', 'Service'), ('Recherche', 'Recherche'), ('Composante', 'Composante Universitaire')], default='', help_text="Type d'affiliation", max_length=20),
        ),
        migrations.CreateModel(
            name='SpecificMaterialInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ref_int', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_num', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.SpecificMaterial')),
            ],
        ),
        migrations.AddField(
            model_name='specificmaterial',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificmaterials', to='core.Entity'),
        ),
        migrations.AddField(
            model_name='specificmaterial',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='specificmaterials', to='core.Tag'),
        ),
        migrations.CreateModel(
            name='GenericMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ref_int', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_man', models.CharField(blank=True, max_length=50, null=True)),
                ('localisation', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genericmaterials', to='core.Entity')),
                ('tags', models.ManyToManyField(blank=True, related_name='genericmaterials', to='core.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
