# Generated by Django 3.0.5 on 2020-05-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200519_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericmaterial',
            old_name='ref_man',
            new_name='ref_mat',
        ),
        migrations.RenameField(
            model_name='specificmaterial',
            old_name='ref_man',
            new_name='ref_mat',
        ),
    ]
