"""
Copyright (C) 2020-2024 LIG Université Grenoble Alpes


This file is part of Matos.

Matos is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

FacManager is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with FacManager. If not, see <https://www.gnu.org/licenses/>

@author Germain Lemasson
@author Clément Lesaulnier
@author Robin Courault
"""
# Generated by Django 3.0.5 on 2020-06-05 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200529_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'En Attente'), (2, 'Demandé'), (3, 'Accepté'), (4, 'Refusé')])),
                ('checkout_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='LoanGenericItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Loan')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GenericMaterial')),
            ],
            options={
                'unique_together': {('loan', 'material')},
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='generic_materials',
            field=models.ManyToManyField(blank=True, related_name='loans', through='core.LoanGenericItem', to='core.GenericMaterial'),
        ),
        migrations.AddField(
            model_name='loan',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='core.Loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='specific_materials',
            field=models.ManyToManyField(blank=True, related_name='loans', to='core.SpecificMaterialInstance'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
