# Generated by Django 3.1.1 on 2020-09-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200605_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmaterial',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Demandé'), (3, 'Accepté'), (4, 'Refusé')]),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
