# Generated by Django 3.0.3 on 2020-02-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200206_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='reference',
            field=models.CharField(help_text='Enter Family Reference', max_length=150),
        ),
        migrations.AlterField(
            model_name='family',
            name='unit',
            field=models.CharField(help_text='Enter Family Unit ', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='reference',
            field=models.CharField(help_text='Enter Location Reference', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(help_text='Enter Product Barcode (ISBN, UPC ...)', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Enter Product Stock Keeping Unit', max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='barcode',
            field=models.CharField(help_text='Enter Product Barcode (ISBN, UPC ...)', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sku',
            field=models.CharField(help_text='Enter Product Stock Keeping Unit', max_length=130),
        ),
    ]
