# Generated by Django 3.0.5 on 2020-10-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200930_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterUniqueTogether(
            name='genericmaterial',
            unique_together={('name', 'entity')},
        ),
        migrations.AlterUniqueTogether(
            name='specificmaterial',
            unique_together={('name', 'entity')},
        ),
        migrations.AlterUniqueTogether(
            name='specificmaterialinstance',
            unique_together={('name', 'model')},
        ),
    ]
