# Generated by Django 3.0.3 on 2020-02-21 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_person_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'Partially returned'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved'), ('c', 'Modified')], default='m', help_text='Product availability', max_length=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Product')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
