# Generated by Django 3.0.3 on 2020-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='imprint',
        ),
        migrations.AddField(
            model_name='productinstance',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
