# Generated by Django 3.0.3 on 2020-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200221_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refUsine',
            field=models.CharField(blank=True, help_text='Product Manufacturing', max_length=200),
        ),
    ]
