# Generated by Django 4.1.7 on 2024-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
