# Generated by Django 3.0.3 on 2020-02-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_product_unitcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='description',
        ),
        migrations.RemoveField(
            model_name='family',
            name='minQuantity',
        ),
        migrations.RemoveField(
            model_name='family',
            name='unit',
        ),
    ]
