# Generated by Django 3.0.3 on 2020-03-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200227_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='orga_type',
        ),
        migrations.AddField(
            model_name='organization',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='affiliation', to='core.Affiliation'),
        ),
        migrations.DeleteModel(
            name='OrganizationType',
        ),
    ]
