# Generated by Django 3.0.3 on 2020-03-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_person_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('manage_entity', 'Can modify an entity')]},
        ),
    ]
