# Generated by Django 3.0.3 on 2020-03-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200303_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
