# Generated by Django 3.0.5 on 2020-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200420_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.AlterField(
            model_name='entity',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='entities', to='core.Affiliation'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductInstance',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
