# Generated by Django 3.0.3 on 2020-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200206_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, help_text='Enter Product Stock Keeping Unit', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, choices=[('ns', 'New Stock'), ('ur', 'Usable Return'), ('nr', 'Unusable Return'), ('ul', 'Usable Lend')], default='ns', help_text='Reason for transaction', max_length=2),
        ),
    ]
