# Generated by Django 3.0.3 on 2020-02-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200226_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unitCost',
        ),
    ]
