# Generated by Django 3.0.3 on 2020-03-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200302_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='status',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='type',
            field=models.CharField(blank=True, choices=[('Labo', 'Laboratoire'), ('Ecole', 'Ecole'), ('Platforme', 'Platforme')], default='', help_text="Type d'affiliation", max_length=20),
        ),
    ]
