# Generated by Django 3.0.3 on 2020-03-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200304_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='family',
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ManyToManyField(related_name='families', to='api.Family'),
        ),
    ]
