# Generated by Django 3.0.3 on 2020-03-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200306_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='families',
            field=models.ManyToManyField(to='api.Family'),
        ),
    ]
