# Generated by Django 3.0.3 on 2020-03-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200306_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='material',
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='api.Family'),
        ),
    ]
