# Generated by Django 3.0.4 on 2020-03-23 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_auto_20200309_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='managed',
            field=models.ManyToManyField(blank=True, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
