# Generated by Django 3.0.5 on 2020-04-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200414_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='superuser',
            new_name='acceptance',
        ),
    ]
