# Generated by Django 3.0.5 on 2020-04-20 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_auto_20200414_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Entity',
        ),
    ]
